__all__ = [
	"GET_INTERNAL_ALERT_TEXT",
	"OSN_SWITCH_CONTEXT_KEY",
	"UPLOAD_INTERNAL_FILE"
]

GET_INTERNAL_ALERT_TEXT = "BRIDGE.GET_INTERNAL_ALERT_TEXT"
UPLOAD_INTERNAL_FILE = "BRIDGE.UPLOAD_INTERNAL_FILE"

OSN_SWITCH_CONTEXT_KEY = "OSN_SWITCH_CONTEXT"
