from typing import (
	Any,
	Callable,
	Dict,
	Optional
)


__all__ = [
	"CURRENT_BROWSING_CONTEXT_TYPEHINT",
	"MAP_REQUEST_FUNCTION_TYPEHINT",
	"MAP_RESPONSE_FUNCTION_TYPEHINT",
	"REQUEST_PARAMS_TYPEHINT"
]

CURRENT_BROWSING_CONTEXT_TYPEHINT = Optional[str]
REQUEST_PARAMS_TYPEHINT = Optional[Dict[str, Any]]

MAP_REQUEST_FUNCTION_TYPEHINT = Callable[[REQUEST_PARAMS_TYPEHINT, str], Dict[str, Any]]
MAP_RESPONSE_FUNCTION_TYPEHINT = Callable[[Dict[str, Any], REQUEST_PARAMS_TYPEHINT], Dict[str, Any]]
